-- MySQL Script generated by MySQL Workbench
-- Thu Jul 21 08:38:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema user_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_schema` DEFAULT CHARACTER SET utf8 ;
USE `user_schema` ;

-- -----------------------------------------------------
-- Table `user_schema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_schema`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `room_no` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_schema`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_schema`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cost` FLOAT NULL,
  `weight` FLOAT NULL,
  `fragile` TINYINT NULL,
  `quantity` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user_schema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
